name: Build Flatpak

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: sysmonitorpro.flatpak
        manifest-path: io.github.george0884.SysMonitorPro.json
        repository-name: flathub
        repository-url: https://flathub.org/repo/flathub.flatpakrepo
